### ISSUE TITLE
El CSAM avanza de 1, no de a 4

### ISSUE THREAD

**Issue by stephanieizquierdo** [Lukas-De-Angelis-Riva/Estructura-Assembly#5]
https://github.com/Lukas-De-Angelis-Riva/66.70-Estructura-del-computador/tree/master/Guia7/Ejercicio06#detalles
En el punto 2 dice "En caso de que el CSAMux reciba 00 irá a la microinstrucción siguiente, es decir, 4 palabras de 41bits más adelante (Que lee desde el CSAI)." esto es erroneo.  No es "4 palabras de 41 mas adelante", es la palabra siguiente.

Segun el libro de Murdocca (ver pagina  232 https://theswissbay.ch/pdf/Gentoomen%20Library/Computer%20Architecture/Principles%20of%20Computer%20Architecture%20-%201999.pdf  ) (segun el paginado del libro seria la pagina 212)

"The Next input to the CS Address MUX is computed by the control store address incrementer (CSAI) shown in Figure 6-10,
which increments the current output of the CS Address MUX by 1."

Esto tambien fue aclarado en las recientes clases de Mazzeo.

**Comment by Lukas-De-Angelis-Riva** [comment]
Arreglado en [@28a3136](https://github.com/Lukas-De-Angelis-Riva/66.70-Estructura-del-computador/commit/28a3136e1ccde873dda8a473d8a75b80ea05cfa6)

Gracias!
